version: "3.8"

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend.env
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    container_name: backend
    image: backend
    build:
      context: /backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./backend.env
    ports:
      - 3000:80

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=casestudy
    volumes:
    - db-data:/var/lib/postgresql/data
    env_file:
      - ./postgres.env

volumes:
  db-data:
