"""created reservations table

Revision ID: 936111e7c749
Revises: b45b3ceb2d9b
Create Date: 2022-03-23 12:39:15.353384

"""
from alembic import op
import sqlalchemy as sa
from app.models.reservation import FacilitiesEnum

# revision identifiers, used by Alembic.
revision = '936111e7c749'
down_revision = 'b45b3ceb2d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.Enum('Swimming Pool', 'Gym', 'Tennis Court', 'Conference Room', name='facilities_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    FacilitiesEnum.drop(op.get_bind())
    # ### end Alembic commands ###
